import{S as $,i as C,a as I}from"./assets/vendor-DEenWwFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();function p(e,o){if(e.hits&&e.hits.length>0){const s=e.hits.map(({webformatURL:t,largeImageURL:r,likes:c,views:w,comments:S,downloads:v,tags:q})=>{const E=q.split(",").join(", ");return`<div class="card">
              <a href="${r}">
                <img src="${t}" alt="${E}" />
              </a>
            <div class="card-properties">
                <ul class="card-list">
                    <li>Likes <span class="accent-item">${c}</span></li>
                    <li>Views <span class="accent-item">${w}</span></li>
                    <li>Comments <span class="accent-item">${S}</span></li>
                    <li>Downloads <span class="accent-item">${v}</span></li>
                </ul>
            </div>
            </div>`}).join("");o.insertAdjacentHTML("beforeend",s),new $(".card-container a",{captionsData:"alt",captionDelay:250}).refresh()}else f("Sorry, there are no images matching your search query. Please try again!")}function g(e){e.style.display="block"}function y(e){e.style.display="none"}function f(e){C.error({message:e,position:"topRight",titleColor:"white",messageColor:"white",timeout:5e3,backgroundColor:"#EF4040"})}async function L(e,o=1,s=15){const n="https://pixabay.com/api/",t="48242250-abd806f4b021d280ea207da17";try{return(await I.get(n,{params:{key:t,q:e,image_type:"photo",per_page:s,page:o,orientation:"horizontal",safesearch:!0}})).data}catch(r){throw new Error(`Error fetching images: ${r.message}`)}}const u=document.querySelector(".card-container"),P=document.querySelector(".search-form"),h=document.querySelector(".loader"),a=document.querySelector(".btn-load");let i=1,l=40,d="",m=0;P.addEventListener("submit",M);a.addEventListener("click",O);async function M(e){e.preventDefault();const o=e.currentTarget;if(d=o.elements.query.value.trim(),!d){f("Please enter a valid search query.");return}i=1,u.innerHTML="",g(h),a.classList.add("is-hidden");try{const s=await L(d,i,l);p(s,u),m=s.totalHits,m>l?a.classList.remove("is-hidden"):a.classList.add("is-hidden"),i+=1}catch{b()}finally{o.reset(),y(h)}}async function O(){if(i>Math.ceil(m/l)){iziToast.error({position:"topRight",message:"We're sorry, there are no more posts to load"}),a.classList.add("is-hidden");return}g(h);try{const e=await L(d,i,l);p(e,u);const o=u.querySelector("li");if(o){const{height:s}=o.getBoundingClientRect();T(s*8,0)}i+=1,i>Math.ceil(m/l)&&(a.classList.add("is-hidden"),iziToast.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"blue"}))}catch{b()}finally{y(h)}}function b(){f("Sorry, there was an error with the request. Please try again later.")}function T(e,o=0){window.scrollBy({top:e,left:o,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
