import{S as C,i as I,a as M}from"./assets/vendor-DEenWwFD.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();function g(e,s){if(e.hits&&e.hits.length>0){const o=e.hits.map(({webformatURL:t,largeImageURL:r,likes:l,views:S,comments:v,downloads:q,tags:E})=>{const $=E.split(",").join(", ");return`<div class="card">
              <a href="${r}">
                <img src="${t}" alt="${$}" />
              </a>
            <div class="card-properties">
                <ul class="card-list">
                    <li>Likes <span class="accent-item">${l}</span></li>
                    <li>Views <span class="accent-item">${S}</span></li>
                    <li>Comments <span class="accent-item">${v}</span></li>
                    <li>Downloads <span class="accent-item">${q}</span></li>
                </ul>
            </div>
            </div>`}).join("");s.insertAdjacentHTML("beforeend",o),new C(".card-container a",{captionsData:"alt",captionDelay:250}).refresh()}else f("Sorry, there are no images matching your search query. Please try again!")}function y(e){e.style.display="block"}function L(e){e.style.display="none"}function f(e){I.error({message:e,position:"topRight",titleColor:"white",messageColor:"white",timeout:5e3,backgroundColor:"#EF4040"})}async function b(e,s=1,o=40){const c="https://pixabay.com/api/",t="48242250-abd806f4b021d280ea207da17";try{return(await M.get(c,{params:{key:t,q:e,image_type:"photo",per_page:o,page:s,orientation:"horizontal",safesearch:!0}})).data}catch(r){throw new Error(`Error fetching images: ${r.message}`)}}const h=document.querySelector(".card-container"),P=document.querySelector(".search-form"),m=document.querySelector(".loader"),n=document.querySelector(".btn-load");let i=1,d=40,u="",a=0,p=120;P.addEventListener("submit",x);n.addEventListener("click",O);async function x(e){e.preventDefault();const s=e.currentTarget;if(u=s.elements.query.value.trim(),!u){f("Please enter a valid search query.");return}i=1,h.innerHTML="",y(m),n.classList.add("is-hidden");try{const o=await b(u,i,d);g(o,h),a=o.totalHits,a>p&&(a=p),i+=1,i<=Math.ceil(a/d)?n.classList.remove("is-hidden"):n.classList.add("is-hidden")}catch{w()}finally{s.reset(),L(m)}}async function O(){if(i>Math.ceil(a/d)){iziToast.error({position:"topRight",message:"We're sorry, there are no more posts to load"}),n.classList.add("is-hidden");return}y(m);try{const e=await b(u,i,d);g(e,h);const s=h.querySelector("li");if(s){const{height:o}=s.getBoundingClientRect();T(o*8,0)}i+=1,i>Math.ceil(a/d)&&(n.classList.add("is-hidden"),iziToast.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"blue"}))}catch{w()}finally{L(m)}}function w(){f("Sorry, there was an error with the request. Please try again later.")}function T(e,s=0){window.scrollBy({top:e,left:s,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
